### ISSUE TITLE
Identify requirement options for mounting

### ISSUE THREAD

**Issue by rmaguire31** [rmaguire31/l3-design-project#23]
Including mounting cartridge and tonearm.

**Comment by GeorgeArthurHall** [comment]
![cartridge](https://user-images.githubusercontent.com/25461755/32997363-2041ad94-cd87-11e7-9316-01edc22368de.png)
![mount](https://user-images.githubusercontent.com/25461755/32997364-206d4472-cd87-11e7-8f30-ab5d809561c6.png)
![mount3](https://user-images.githubusercontent.com/25461755/32997365-2093b788-cd87-11e7-8f64-746284e1f4a6.png)

[mounting-requirements.pdf](https://github.com/rmaguire31/l3-design-project/files/1486122/mounting-requirements.pdf)
<img width="639" alt="table" src="https://user-images.githubusercontent.com/25461755/32997366-2110b1c0-cd87-11e7-9a95-4856812d27ca.png">
issue #23 closed
